# in debug_mode no agent directories will be created and no models will be saved
debug_mode: false

# Hardware specifc configurations
# number of parallel environments
n_envs: 15
# gpu yes or no
no_gpu: no


### Global configuration that applies to all robots
# navigation task mode, chose from "random" or "staged"
task_mode: "cases"
# number of simulation timesteps
n_timesteps: 40000000
max_num_moves_per_eps: 400

periodic_eval:
  # max number of steps per episode
  max_num_moves_per_eps: 450 # 1000
  # number of evaluation episodes
  n_eval_episodes: 40 # 100
  # evaluation frequency, evaluation after every n_envs * 20000 timesteps
  eval_freq: 3000 # 20000

### training_curriculum
# threshold metric to be considered during evaluation
# can be either "succ" (success rate) or "rew" (reward)
training_curriculum:
  # file for the robot's learning curriculum
  training_curriculum_file: "marl_warehouse.yaml"
  threshold_type: "succ"
  upper_threshold: 0.8
  lower_threshold: 0.35

### evaluation_curriculum
# threshold metric to be considered during evaluation
# can be either "succ" (success rate) or "rew" (reward)
evaluation_curriculum:
  # file for the robot's learning curriculum
  evaluation_curriculum_file: "marl_warehouse.yaml"
  threshold_type: "succ"
  upper_threshold: 0.8
  lower_threshold: 0.35

### stop training on threshold
# stops training when last stage reached and threshold satisfied
stop_training:
  threshold_type: "succ"
  threshold: 0.95


### logging
# log interval
log_interval: 1
# save evaluation stats during training in log file
eval_log: false
# use tensorboard
tb: true
# use wandb
wandb: true

global_tasks: true

robots:
  jackal:
    # number of robots of this type
    num_robots: 4
    # name of hyperparameter file located in the configs/hyperparameters directory
    hyperparameter_file: "jackal.json" # "default.json"
    # name of architecture defined in the Policy factory
    architecture_name: "AGENT_26"

    # path to latest checkpoint; if provided the training will be resumed from that checkpoint
    #resume: "/home/frank/MARL_ws/src/planners/rosnav/agents/MARL_AGENTS_2023_04_06__18_19/jackal_2023_04_06__18_19"
    resume: "/home/frank/MARL_ws/src/planners/rosnav/agents/backup3/jackal_2023_04_13__14_53"
    #resume: null
    #resume: "/home/frank/MARL_ws/src/planners/rosnav/agents/MARL_AGENTS_2023_04_04__13_58/jackal_2023_04_04__13_58"
    ##resume: "/home/frank/MARL_ws/src/planners/rosnav/agents/MARL_AGENTS_2023_03_08__18_03/jackal_2023_03_08__18_03"
    ##resume : "/home/frank/MARL_ws/src/planners/rosnav/agents/MARL_AGENTS_2023_01_09__16_13/jackal_2023_01_09__16_13"
    #resume: "/home/frank/MARL_ws/src/planners/rosnav/agents/best_comm_model/jackal_2023_02_28__15_19"
  # rto:
  #   # number of robots of this type
  #   num_robots: 3
  #   # name of hyperparameter file located in the configs/hyperparameters directory
  #   hyperparameter_file: "rto.json"
  #   # name of architecture defined in the Policy factory
  #   architecture_name: "AGENT_24"
  #   # path to latest checkpoint; if provided the training will be resumed from that checkpoint
  #   resume: null
  